name: Deploy Hugo site to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-22.04   # pin GitHub runner OS

    defaults:
      run:
        working-directory: ./hugo/vincentdevelops

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Hugo (extended)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          eval "$(ssh-agent -s)"

          # Write private key to file
          umask 077
          cat > ~/.ssh/id_ed25519_gha <<'KEY'
          ${{ secrets.SSH_PRIVATE_KEY }}
          KEY
          chmod 600 ~/.ssh/id_ed25519_gha
          ssh-add ~/.ssh/id_ed25519_gha

          # Optional sanity check
          ssh-add -l

      - name: Rsync to VPS
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          WEBROOT:  ${{ secrets.WEBROOT }}
        run: |
          rsync -az --delete ./public/ "${SSH_USER}@${SSH_HOST}:${WEBROOT}/"